IAV-2209: Update styleguide with form elements
LaakarikeskusAava/styleguide pull request #16
Opened 2017-03-24 07:43 UTC by kallevu

- Adds `:active` and `:hover` styles for form elements.
- Unifies colors.
- Adds Chosen.js library for select element.

2017-03-24 07:47 UTC, lauriii commented
![screenshot from 2017-03-24 18-45-39](https://cloud.githubusercontent.com/assets/1845495/24284989/272cbd06-10c2-11e7-80e2-c90786c8877b.png)
Should we add some padding here?

![screenshot from 2017-03-24 18-45-51](https://cloud.githubusercontent.com/assets/1845495/24284988/27295cd8-10c2-11e7-83f3-e2c2d974cf21.png)
Should we add some margin between buttons?

![screenshot from 2017-03-24 18-45-43](https://cloud.githubusercontent.com/assets/1845495/24284987/2728ea50-10c2-11e7-9ac7-648c861b18df.png)
Maybe some nicer test content would be useful here (this is a public website)

2017-03-24 07:53 UTC, juhog commented
Textarea padding, see this commit: https://github.com/druidfi/aava/pull/43/commits/d5a4d2644bb2c27ba99adc3a3783675c51a87967

2017-03-26 02:44 UTC, juhog commented
I fixed the textarea padding issue (styleguide commit https://github.com/LaakarikeskusAava/styleguide/pull/16/commits/2e7fcbc87b9dbdaa7f9adb7777051b3ef4b875c0).

2017-03-26 02:44 UTC, juhog commented
Form element font-sizes are not set. I'm gonna fix that.

<img width="806" alt="screen shot 2017-03-26 at 09 42 16" src="https://cloud.githubusercontent.com/assets/1115979/24328008/cad878b8-1208-11e7-88f2-165cb4fcc309.png">

2017-03-26 03:01 UTC, juhog commented
Buttons now have margin-right 0.5em.

<img width="270" alt="screen shot 2017-03-26 at 09 59 41" src="https://cloud.githubusercontent.com/assets/1115979/24328120/2ff2dad4-120b-11e7-9c60-9509dcd4316e.png">

2017-03-26 03:12 UTC, juhog commented
Radio button options are now "Option A" and "Option B": https://github.com/LaakarikeskusAava/styleguide/pull/16/commits/c5fd92fabdb500db95d8da23984ca05109ea6d8a

2017-03-26 04:55 UTC, juhog requested changes
Header button (Online ajanvaraus) seems to be missing. Other than that looks good.

2017-03-28 07:26 UTC, juhog commented on styles/components/buttons/buttons.scss
> +@media screen and (min-width: 769px) {
@lauriii Miten tehään responsive tyylien kanssa styleguidessa? Tässä ensimmäinen tilanne missä on tulossa media-querya styleguideen.

2017-03-30 11:52 UTC, juhog approved these changes

2017-03-30 11:52 UTC, merged