Added example of an table
LaakarikeskusAava/styleguide pull request #9
Opened 2016-11-30 10:55 UTC by bountyh

2016-12-06 15:33 UTC, juhog requested changes
1) Variaatiot

Mobile tablesta on eri variaatioita. Miten saadaan ne näkyviin styleguideen? Onko pakko duplikoida .twig file?

----

2) Mobileheaders variaatio

Näyttää keskeneräiseltä. Labelit on positioitu omituisesti.

<img width="785" alt="screen shot 2016-12-06 at 22 18 47" src="https://cloud.githubusercontent.com/assets/1115979/20931555/124b7aa2-bc04-11e6-8400-d9fa441fa22a.png">

----

3) Mobile single column variaatio

Mitä on tarkotus tapahtua jos pistää päälle mobile-headers ja mobile-single-column? Nyt tekstiä tulostuu päällekkäin.

<img width="795" alt="screen shot 2016-12-06 at 22 17 52" src="https://cloud.githubusercontent.com/assets/1115979/20931567/1fdac632-bc04-11e6-8c17-c27e69354086.png">

----

4) Styleguide markupin white-spacet

Varsinkin mobile taulukon markuppiin tulee paljon ihmeellistä white-spacea eikä markupista saa oikeen enää selvää. Pystytäänkö kontrolloimaan tota markuppia niin että siitä sais paremmin selvää?

<img width="788" alt="screen shot 2016-12-06 at 22 18 59" src="https://cloud.githubusercontent.com/assets/1115979/20931575/2ab73e3c-bc04-11e6-889d-3a68508a280c.png">

----

Voi tulla vielä muuta kommentoitavaa sen jälkeen kun noi yllä olevat asiat on ensin selvinny.

2016-12-07 16:05 UTC, lauriii commented
Tällä hetkellä ei oo suunitelmissa tehdä noin leveitä labeleita kun mitä sulla on tossa kuvassa. Katsotaan siinä tapauksessa jos tulee vastaan noita leveämpiä labeleita.

Korjasin sisennykset uuteen single column tableen mutta ton normaalin mobile tablen sisennyksiä on hankala korjata koska KSS Twig spaceless on rikki.

2016-12-07 18:33 UTC, juhog requested changes
Sekalaisia ajatuksia, koska en ihan ymmärrä tätä mobiili-tablejen lähestymistapaa:

1) Mobile single column table on käytännössä ihan vaan lista. Tarviiko sen olla `<table>` ollenkaan?

2) Mobile tablekin on käytännössä vaan lista. Tablessa ja table-celleissä on se etu että saadaan sama leveys ekalle columnille. Mutta käytännössä se halutaan pitää tietyn levyisenä joten se vois olla ihan vaan div ja % leveys.

3) `.table--mobile-headers` on table, mutta siinä ei varsinaisesti käytetä `<table>` elementtiä. Jos kerran käytetään tablea, niin ne header labelit vois olla ihan oikeitakin cellejä.

----

Tärkeimpänä pointtina tässä se, että nää asiat voi tulla vastaan sitten jos/kun näitä table-koodeja halutaan joskus laajentaa tai rakentaa jotain näiden päälle.

2016-12-07 18:33 UTC, juhog commented on styleguide/public/styles.css
> +  width: 100%;
Tarvitaanko tää kun `.table` tyylillä on jo tää tyyli?

2016-12-07 18:33 UTC, juhog commented on styleguide/public/styles.css
> +  padding-left: 25%;
Tää padding ei vaikuttais tekevän käytännössä mitään. Poistetaan?

2016-12-07 18:33 UTC, juhog commented on styleguide/public/styles.css
> +  width: 25%;
Tää width ei tee paljoa. Käytännössä haluttais ekan cellin leveyksisiä elementtejä. Poistetaan width tyyli?

<img width="1076" alt="screen shot 2016-12-08 at 00 41 03" src="https://cloud.githubusercontent.com/assets/1115979/20979885/faf5a016-bce0-11e6-9a46-daef24c7779d.png">

2016-12-07 18:33 UTC, juhog commented on styleguide/public/styles.css
> +.table--details details {
Mitä nää `details` tyylit on?

2016-12-07 18:33 UTC, juhog commented on styles/components/table/table-mobile.twig
> +        {% if table.mobile_single_column %}
Nyt kun tolla single-columnilla on oma templatensa niin voiko single-column koodit poistaa tästä templatesta?

2016-12-08 09:26 UTC, lauriii commented on styleguide/public/styles.css
> +.table--details details {
Esimerkki tästä löytyy täältä: http://preview.druid.fi/aava-iav-prototype/kuvantaminen/

2016-12-08 09:26 UTC, lauriii commented on styles/components/table/table-mobile.twig
> +        {% if table.mobile_single_column %}
Poistettu

2016-12-08 09:27 UTC, lauriii commented on styleguide/public/styles.css
> +  padding-left: 25%;
Refaktoroin tätä jonkin verran

2016-12-08 09:28 UTC, lauriii commented
1. Joo koska ei haluta kirjottaa sille uusia tyylejä ja ne toimii kätevästi kun käytetään tablea
2. Korjasin tota mobile tablea ja se käyttää nyt sitä tablea oikeesti sen leveyden asettamiseksi.
3. Korjattu

2016-12-08 10:22 UTC, juhog requested changes

2016-12-08 10:22 UTC, juhog commented on styles/components/table/table-mobile.twig
> +      <tbody class="table__row table__row--{{ cycle(['odd', 'even'], loop.index0) }}">
Sisennystä liikaa.

2016-12-08 10:22 UTC, juhog commented on styles/components/table/table-mobile.twig
> +            <tr class="table__sub-row">
En oo varma onko käytännön huolenaihe, mutta teoriassa jos on vaan 1 row, niin `<tr>` tagia ei suljeta.

2016-12-08 10:37 UTC, lauriii commented
Molemmat korjattu

2016-12-08 10:39 UTC, juhog approved these changes

2016-12-08 10:39 UTC, merged